web_profiler:
  toolbar: true

framework:
  profiler:
    collect_serializer_data: true

# test environment override (kept here for dev/test location)
when@test:
  framework:
    profiler: { collect: false }
